version: '2'

services:
   
  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/plex/config:/config
      - ~/movies:/data/movies     
      - ~/tvshows:/data/tvshows
      - ~/plex/transcode:/transcode
    restart: always  

  deluge:
    image: "linuxserver/deluge"
    container_name: deluge
    ports:
      - 8112:8112
      - 51413:51413
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/deluge/config:/config
      - ~/deluge/downloads:/downloads
    restart: always
  
  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    ports:
      - 8989:8989
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/sonarr/config:/config
      - ~/tvshows:/tv
      - ~/deluge/downloads:/downloads

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    ports:
      - 7878:7878
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/radarr/config:/config
      - ~/movies:/movies
      - ~/deluge/downloads:/downloads

  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    ports:
      - 9117:9117
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/jackett/config:/config
      - ~/deluge/downloads:/downloads

  plexpy:
    image: "linuxserver/plexpy"
    container_name: plexpy
    ports:
      - 8181:8181
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/plexpy/config:/config
      - ~/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro

  requests:
    image: "linuxserver/ombi"
    container_name: requests
    ports:
      - 3579:3579
    networks:
      - media
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - ~/requests/config:/config

  organizr:
    image: "lsiocommunity/organizr"
    container_name: organizr
    ports:
      - 80:80
      - 443:443
    networks:
      - media
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ~/organizr/config:/config

networks:
  media:
    driver: bridge